// <auto-generated />
using System;
using HistoryFilesFeeder.Epex.Epex.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HistoryFilesFeeder.Migrations
{
    [DbContext(typeof(IntradayContinuousDbContext))]
    partial class IntradayContinuousDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HistoryFilesFeeder.Epex.IntradayContinuous", b =>
                {
                    b.Property<DateTime>("DeliveryStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryEnd")
                        .HasColumnType("datetime2");

                    b.Property<double?>("HighPrice")
                        .HasColumnType("float");

                    b.Property<double?>("LastPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastPriceTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("LowPrice")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeBuy")
                        .HasColumnType("float");

                    b.Property<double?>("VolumeSell")
                        .HasColumnType("float");

                    b.Property<string>("VolumeUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("WeightedAveragePrice")
                        .HasColumnType("float");

                    b.HasKey("DeliveryStart");

                    b.ToTable("IntradayContinuous");
                });
#pragma warning restore 612, 618
        }
    }
}
